# Generated by Django 5.0.7 on 2024-10-23 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Content: News', 'verbose_name_plural': 'Content: News'},
        ),
        migrations.AlterModelOptions(
            name='mappoint',
            options={'verbose_name': 'Content: Map Point', 'verbose_name_plural': 'Content: Map Points'},
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'Communication: Questions', 'verbose_name_plural': 'Communication: Questions'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Communication: Notification', 'verbose_name_plural': 'Communication: Notifications'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Monitoring: Profile', 'verbose_name_plural': 'Monitoring: Profiles'},
        ),
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'verbose_name': 'Communication: Refund Request', 'verbose_name_plural': 'Communication: Refund Requests'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Communication: Review', 'verbose_name_plural': 'Communication: Reviews'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Content: Features', 'verbose_name_plural': 'Content: Features'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Payment: Stock', 'verbose_name_plural': 'Payment: Stocks'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Payment: Transaction', 'verbose_name_plural': 'Payment: Transactions'},
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(help_text='Recommended resolution: 800x533', upload_to='events_imgs/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='tag',
            field=models.CharField(max_length=225, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='subject',
            field=models.CharField(max_length=225, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_spent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Spent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request date'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaction', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(max_length=225, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='service',
            name='svg_icon',
            field=models.TextField(help_text='Insert SVG code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minimum_purchase_quantity',
            field=models.PositiveIntegerField(verbose_name='Minimum purchase quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price per unit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='remaining_quantity',
            field=models.PositiveIntegerField(verbose_name='Remaining quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_quantity',
            field=models.PositiveIntegerField(verbose_name='Total quantity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
