# Generated by Django 5.0.7 on 2024-07-31 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=2000)),
                ('img', models.ImageField(upload_to='events_imgs/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.CharField(max_length=225)),
            ],
        ),
    ]
