# Generated by Django 5.0.7 on 2024-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='cat_imgs/', verbose_name='800x600'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(upload_to='events_imgs/', verbose_name='800x533'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(upload_to='product_imgs/', verbose_name='800x600'),
        ),
    ]
