# Generated by Django 5.0.7 on 2024-07-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_img_alter_events_img_alter_menu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
