# Generated by Django 5.0.7 on 2024-07-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_tag_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
    ]
