# Generated by Django 5.0.7 on 2024-08-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
