# Generated by Django 5.0.7 on 2024-08-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='date',
        ),
    ]
