# Generated by Django 5.0.7 on 2024-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_message_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('min_quantity', models.PositiveIntegerField(default=3000)),
                ('max_quantity', models.PositiveIntegerField(default=10000)),
            ],
        ),
    ]
