# Generated by Django 5.0.7 on 2024-08-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_category_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
