# Generated by Django 5.0.7 on 2024-08-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
