# Generated by Django 5.0.7 on 2024-08-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
