# Generated by Django 5.0.7 on 2024-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='cat_imgs/', verbose_name='800x600 (рекомендованное разрешение)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=225, null=True, verbose_name='Тег'),
        ),
    ]
