# Generated by Django 5.0.7 on 2024-08-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_category_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Контент: Категория', 'verbose_name_plural': 'Контент: Категории'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Контент: Событие', 'verbose_name_plural': 'Контент: События'},
        ),
        migrations.AlterModelOptions(
            name='mappoint',
            options={'verbose_name': 'Контент: Точка на карте', 'verbose_name_plural': 'Контент: Точки на карте'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Контент: Товар в меню', 'verbose_name_plural': 'Контент: Товары в меню'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Коммуникация: Уведомление', 'verbose_name_plural': ' Коммуникация: Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Контент: Партнер', 'verbose_name_plural': 'Контент: Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Мониторинг: Профиль', 'verbose_name_plural': 'Мониторинг: Профили'},
        ),
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'verbose_name': 'Коммуникация: Запрос на возврат', 'verbose_name_plural': 'Коммуникация:  Запросы на возврат'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Коммуникация: Отзыв', 'verbose_name_plural': 'Коммуникация: Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Оплата: Акция', 'verbose_name_plural': 'Оплата: Акции'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Оплата: Транзакция', 'verbose_name_plural': 'Оплата: Транзакции'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
