# Generated by Django 5.0.7 on 2024-08-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_category_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='remaining_quantity',
            field=models.PositiveIntegerField(verbose_name='Оставшееся количество'),
        ),
    ]
