# Generated by Django 5.0.7 on 2024-08-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_stock_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='minimum_purchase_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Минимальное количество для покупки'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Оставшееся количество'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общее количество'),
        ),
    ]
