# Generated by Django 5.0.7 on 2024-08-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_stock_minimum_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='minimum_purchase_quantity',
            field=models.PositiveIntegerField(verbose_name='Минимальное количество для покупки'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='remaining_quantity',
            field=models.PositiveIntegerField(verbose_name='Оставшееся количество'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_quantity',
            field=models.PositiveIntegerField(verbose_name='Общее количество'),
        ),
    ]
