# Generated by Django 5.0.7 on 2024-09-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_stock_minimum_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
