# Generated by Django 5.0.7 on 2024-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delete_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=2000)),
                ('svg_icon', models.TextField(help_text='Вставте SVG код')),
            ],
            options={
                'verbose_name': 'Контент: Услуга',
                'verbose_name_plural': 'Контент: Услуги',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
