# Generated by Django 5.0.7 on 2024-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_service_remove_menu_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed')], default=1, max_length=100, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_checkout_id',
            field=models.CharField(max_length=500, null=True, verbose_name='stripe_id'),
        ),
    ]
