# Generated by Django 5.0.7 on 2024-09-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_transaction_status_transaction_stripe_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
