# Generated by Django 5.0.7 on 2024-09-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Контент: Новости', 'verbose_name_plural': 'Контент: Новости'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Контент: Возможности', 'verbose_name_plural': 'Контент: Возможности'},
        ),
    ]
