# Generated by Django 5.0.7 on 2024-09-09 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_massage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='massage',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Сообщение'),
        ),
    ]
