# Generated by Django 5.0.7 on 2024-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_review_email_remove_review_name_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='На общую сумму'),
        ),
    ]
