# Generated by Django 5.0.7 on 2024-09-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_profile_balance_profile_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_spent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='На общую сумму'),
        ),
    ]
